apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-sample
spec:
  entrypoint: python app/main.py --num_chanel 3 --width 112 --height 112 --chunk_size 1 --num_worker 10 --alpha 0.0001
  runtimeEnvYAML: |
    pip:
      - requests==2.26.0
      - pendulum==2.1.2
    env_vars:
      counter_name: "test_counter"
  rayClusterSpec:
    rayVersion: '2.9.0' 
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
            - name: ray-head
              image: test:latest
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # 
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: "1"
                requests:
                  cpu: "200m"
              volumeMounts:
                - mountPath: app
                  name: main
          volumes:
            - name: main
              configMap:
                name: main
                items:
                  - key: app/main.py
                    path: app/main.py
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 0
        maxReplicas: 5
        groupName: small-group
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: test:latest
                lifecycle:
                  preStop:
                    exec:
                      command: [ "/bin/sh", "-c", "ray stop" ]
                resources:
                  limits:
                    cpu: "1"
                  requests:
                    cpu: "200m"
